apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aqua-agent
  namespace: aqua
  labels:
    app: aqua-agent
    aqua.component: enforcer
  
spec:
  selector:
    matchLabels:
      app: aqua-agent
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/aqua-agent: unconfined
      labels:
        app: aqua-agent
        aqua.component: enforcer
      name: aqua-agent
      namespace: aqua
    spec:
      serviceAccount: aqua-sa
      serviceAccountName: aqua-sa
      containers:
      - name: aqua-agent
        image: "registry.aquasec.com/enforcer:2022.4"
        imagePullPolicy: "Always"
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
            - NET_RAW
            - SYS_PTRACE
            - KILL
            - MKNOD
            - SETGID
            - SETUID
            - SYS_MODULE
            - AUDIT_CONTROL
            - SYSLOG
            - SYS_CHROOT
            - SYS_RESOURCE
            - IPC_LOCK
            - LINUX_IMMUTABLE
            - CHOWN
            - DAC_OVERRIDE
            - FSETID
            - FOWNER
            - SETFCAP
            - SETPCAP
            - NET_BIND_SERVICE
            - AUDIT_WRITE
            - IPC_LOCK
          privileged: false
        envFrom:
        - configMapRef:
            name: aqua-csp-enforcer
        env:
        - name: AQUA_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: AQUA_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: enforcer-token
              optional: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run
          name: var-run
        - mountPath: /dev
          name: dev
        - mountPath: /host/sys
          name: sys
          readOnly: true
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/etc
          name: etc
          readOnly: true
        - mountPath: /host/opt/aquasec
          name: aquasec
          readOnly: true
        - mountPath: /opt/aquasec/tmp
          name: aquasec-tmp
        - mountPath: /opt/aquasec/audit
          name: aquasec-audit
        - mountPath: /data
          name: aquasec-data
        - mountPath: /var/autopilot/addon/containers
          name: containers
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8096
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readinessz
            port: 8096
          initialDelaySeconds: 60
          periodSeconds: 30
        ports:
        - containerPort: 8096
          protocol: TCP
        resources:
          requests:
            cpu: 350m
            memory: 512Mi

      dnsPolicy: ClusterFirst
      hostPID: true
      imagePullSecrets:
      - name: aqua-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run
          type: ""
        name: var-run
      - hostPath:
          path: /dev
          type: ""
        name: dev
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - name: etc
        hostPath:
          path: /etc
          type: ""
      - name: aquasec
        hostPath:
          path:  /var/autopilot/addon/aquasec
          type: ""
      - name: aquasec-tmp
        hostPath:
          path:  /var/autopilot/addon/aquasec/tmp
          type: ""
      - name: aquasec-audit
        hostPath:
          path:  /var/autopilot/addon/aquasec/audit
          type: ""
      - name: aquasec-data
        hostPath:
          path:  /var/autopilot/addon/aquasec/data
          type: ""
      - name: containers
        hostPath:
          path:  /var/autopilot/addon/containers
          type: ""
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate