apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: aqua-windows-agent
    aqua.component: enforcer
  name: aqua-windows-agent
  namespace: aqua
spec:
  selector:
    matchLabels:
      app: aqua-windows-agent
  template:
    metadata:
      labels:
        app: aqua-windows-agent
        aqua.component: windows-enforcer
      name: aqua-windows-agent
      namespace: aqua
      annotations:
        container.apparmor.security.beta.kubernetes.io/aqua-windows-agent: unconfined
    spec:
      containers:
      - env:
        - name: AQUA_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: AQUA_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: windows-enforcer-token
              optional: true
        envFrom:
        - configMapRef:
            name: aqua-csp-windows-enforcer
        image: registry.aquasec.com/windows-enforcer:2022.4
        command:
        - powershell.exe
        - -command
        - $Installation = Get-WmiObject -Class Win32_Product | Where-Object {$_.Vendor -eq "Aqua Security"};
        - if ($Installation -ne $null) {
            Get-ChildItem -Path "C:\Program Files\AquaSec\log";
            Write-Output "Backing up Aqua-Enforcer logs to $Env:TEMP\Aquasec\";
            Copy-Item -Path "C:\Program Files\AquaSec\log" -Destination "$Env:TEMP\Aquasec" -Recurse -Force -ErrorAction SilentlyContinue;
            Write-Output "Removing $Installation.Name...";
            $argList=@("/X",$Installation.IdentifyingNumber,"/qn","/L $Env:TEMP\Aquasec\AquaAgentWindowsInstaller.remove.log","/norestart","MSIRESTARTMANAGERCONTROL=Disable");
            $Process=Start-Process -FilePath msiexec.exe -ArgumentList $argList -NoNewWindow -PassThru -Wait;
          };
        - Write-Output "List $Env:CONTAINER_SANDBOX_MOUNT_POINT";
        - Get-ChildItem -Path $Env:CONTAINER_SANDBOX_MOUNT_POINT;
        - Copy-Item -Path $(Join-Path -Path "$Env:CONTAINER_SANDBOX_MOUNT_POINT" -ChildPath "\AquaAgentWindowsInstaller.msi") -Destination $(Join-Path -Path "$Env:TEMP" -ChildPath "\AquaAgentWindowsInstaller.msi") -Force;
        - $argList=@("/I","$Env:TEMP\AquaAgentWindowsInstaller.msi","/qn","/L*V AquaAgentWindowsInstaller.install.log");
        - $sysEnv=@(Get-ChildItem -Path Env:) | ForEach { $argList+=$_.Name+'="'+$_.Value+'"' };
        - Write-Output "Running Start-Process -FilePath msiexec.exe -ArgumentList " $argList " -NoNewWindow -PassThru -Wait";
        - $Process=Start-Process -FilePath msiexec.exe -ArgumentList $argList -NoNewWindow -PassThru -Wait;
        - Get-Content AquaAgentWindowsInstaller.install.log;
        - While ( $true ){ Start-Sleep -s 30 }
        imagePullPolicy: Always
#        resources:
#          limits:
#            cpu: 1000m
#            memory: 1.5Gi
#          requests:
#            cpu: 350m
#            memory: 512Mi
        startupProbe:
          exec:
            command: 
            - powershell.exe
            - -c
            - Get-Service -Name slkd
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          exec:
            command: 
            - powershell.exe
            - -c
            - Get-Service -Name slkd | Where-Object {$_.Status -eq "Running"}
          timeoutSeconds: 5
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command: 
            - powershell.exe
            - -c
            - Start-Process -FilePath "C:\Program Files\AquaSec\slk.exe" -ArgumentList @("health","check") -Wait -NoNewWindow -RedirectStandardOutput "$Env:TEMP\aqua-enforcer-health.check";
            - $connection = Get-Content -Path "$Env:TEMP\aqua-enforcer-health.check" | Select-String "connection to management server";
            - Get-Content -Path "$Env:TEMP\aqua-enforcer-health.check";
            - if ($connection | Select-String "PASSED" -Quiet) {
                  Exit 0;
              };
            - Exit 1;
          timeoutSeconds: 15
          initialDelaySeconds: 15
          periodSeconds: 15
        lifecycle:
          preStop:
            exec:
              command: 
              - powershell.exe
              - -command
              - $Installation = Get-WmiObject -Class Win32_Product | Where-Object {$_.Vendor -eq "Aqua Security"};
              - if ($Installation -ne $null) {
                  Get-ChildItem -Path "C:\Program Files\AquaSec\log";
                  Write-Output "Backing up Aqua-Enforcer logs to $Env:TEMP\Aquasec\";
                  Copy-Item -Path "C:\Program Files\AquaSec\log" -Destination "$Env:TEMP\Aquasec\" -Recurse -Force -ErrorAction SilentlyContinue;
                  Write-Output "Removing $Installation.Name...";
                  $argList=@("/X",$Installation.IdentifyingNumber,"/qn","/L $Env:TEMP\Aquasec\AquaAgentWindowsInstaller.remove.log","/norestart","MSIRESTARTMANAGERCONTROL=Disable");
                  $Process=Start-Process -FilePath msiexec.exe -ArgumentList $argList -NoNewWindow -PassThru -Wait;
                };
        name: aqua-windows-agent
        securityContext:
          windowsOptions:
            hostProcess: true
            runAsUserName: "NT AUTHORITY\\SYSTEM"
      nodeSelector:
        kubernetes.io/os: windows
      hostNetwork: true
      dnsPolicy: ClusterFirst
      hostPID: true
      imagePullSecrets:
       - name: aqua-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: aqua-sa
      serviceAccountName: aqua-sa
      terminationGracePeriodSeconds: 180
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
